# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', max_length=255, upload_to='images'),
            preserve_default=False,
        ),
    ]
